### ISSUE TITLE
Installing DLS forever

### ISSUE THREAD

**Issue by John-Colvin** [d-language-server/vscode-dls#22]
![image](https://user-images.githubusercontent.com/1867189/71814052-3cf0ae80-3073-11ea-9cd3-27449b59492e.png)

never goes away

**Comment by LaurentTreguier** [comment]
Can't reproduce.
What are:
- your OS ?
- your DMD/Dub versions ?

Is DLS supposed to be already installed, or is it supposed to be a fresh installation ?
What happens when trying to run `dub fetch dls; dub run dls:bootstrap` manually ?

**Comment by John-Colvin** [comment]
Windows.

I'm guessing the problem was that dub wasn't on the path (although hanging forever installing wasn't a great response to that situation)

After installing manually (bootstrap) it seems to be working in vscode, so closing this now

Thanks :)

**Comment by LaurentTreguier** [comment]
Ah, that explains it indeed
